//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_BBDD_Bader_Iker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantsDBEntities10 : DbContext
    {
        public RestaurantsDBEntities10()
            : base("name=RestaurantsDBEntities10")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Ciutats> Ciutats { get; set; }
        public virtual DbSet<Continents> Continents { get; set; }
        public virtual DbSet<GaleriaImatges> GaleriaImatges { get; set; }
        public virtual DbSet<Horaris> Horaris { get; set; }
        public virtual DbSet<Paisos> Paisos { get; set; }
        public virtual DbSet<Resenyes> Resenyes { get; set; }
        public virtual DbSet<Reserves> Reserves { get; set; }
        public virtual DbSet<Restaurants> Restaurants { get; set; }
        public virtual DbSet<Usuaris> Usuaris { get; set; }
    }
}
