//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_BBDD_Bader_Iker
{
    using System;
    using System.Collections.Generic;
    
    public partial class GaleriaImatges
    {
        public string nomImatge { get; set; }
        public int idImatge { get; set; }
        public Nullable<int> idRestaurant { get; set; }
    
        public virtual Restaurants Restaurants { get; set; }
    }
}
