//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_BBDD_Bader_Iker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paisos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paisos()
        {
            this.Ciutats = new HashSet<Ciutats>();
        }
    
        public string NomPais { get; set; }
        public string NomContinent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ciutats> Ciutats { get; set; }
        public virtual Continents Continents { get; set; }
    }
}
