//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_BBDD_Bader_Iker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserves
    {
        public int IDReserva { get; set; }
        public string NomRestaurant { get; set; }
        public Nullable<int> idUsuari { get; set; }
        public Nullable<System.DateTime> DataReserva { get; set; }
        public Nullable<System.TimeSpan> HoraReserva { get; set; }
        public Nullable<int> NumeroPersones { get; set; }
    
        public virtual Usuaris Usuaris { get; set; }
        public virtual Restaurants Restaurants { get; set; }
    }
}
